version: '3'

services:

  postgres:
    image: postgres:16.2
    profiles: [dev-postgres]
    container_name: compstore-postgres-keycloak
    restart: always
    ports:
      - '5431:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    networks:
      - compstore_network

  keycloak:
    image: keycloak/keycloak:24.0
    profiles: [dev-postgres]
    container_name: compstore-keycloak
    restart: always
    ports:
      - '8090:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: test
    depends_on:
      postgres:
        condition: service_started
    networks:
      - compstore_network
    command:
      - start-dev

  backend-dev-postgres:
    build:
      context: .
      args:
        - MAVEN_PROFILE=dev-postgres
    profiles: [dev-postgres]
    container_name: compstore-api-postgres
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: dev-postgres
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
      keycloak:
        condition: service_started
    networks:
      - compstore_network

  backend-dev-h2:
    build:
      context: .
      args:
        - MAVEN_PROFILE=dev-h2
    profiles: [dev-h2]
    container_name: compstore-api-h2
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: dev-h2
    restart: unless-stopped

networks:
  compstore_network:
    driver: bridge

volumes:
  pgdata: