server:
  port: 8080

spring:
  profiles:
    active: dev-h2
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true

cors:
  allowed-origins: ${PROD_ALLOWED_FRONTEND:http://localhost:3000}

management:
  endpoints:
    web:
      exposure:
        include: '*'