server:
  port: 8080

spring:
  profiles:
    active: dev-h2
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true