spring:
  datasource:
    url: jdbc:h2:mem:compstoredb
    username: user
    password: test
    driverClassName: org.h2.Driver
  output:
    ansi:
      enabled: always
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true