server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:compstoredb
    username: user
    password: test
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  hibernate:
    ddl-auto: update
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
