spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/compstore-postgres
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: always
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: validate